//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.03 at 10:10:13 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = NameSpace.ORDER, elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.demo.spring.errorhandler.infrastructure.soap.message;

import com.demo.spring.errorhandler.infrastructure.soap.NameSpace;